#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: rundeck:create-project: "create a Rundeck project"
#/ usage: rerun rundeck:create-project [options]

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh create-project || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: rundeck:create-project. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------
if [ -d /var/rundeck/projects/"${NAME}" ]
then
   echo "WARNING, project ${NAME} already exists, doing nothing" 1>&2
   exit 0
fi

projectTmpDir="$(mktemp -d)"

TIMESTAMP="$(date)"

cp -r "${RERUN_MODULE_DIR}"/templates/project/* "${projectTmpDir}"

sed -i \
       -e "s+\${PROJECT_NAME}+${NAME}+g" \
       -e "s+\${TIMESTAMP}+${TIMESTAMP}+g" \
       "${projectTmpDir}"/etc/project.properties

UNAME="$(uname)"
UNAME_m="$(uname -m)"
UNAME_r="$(uname -r)"

sed -i \
       -e "s+\${user}+${USER}+g" \
       -e "s+\${uname}+${UNAME}+g" \
       -e "s+\${uname_m}+${UNAME_m}+g" \
       -e "s+\${uname_r}+${UNAME_r}+g" \
       "${projectTmpDir}"/etc/resources.xml

sudo mv  "${projectTmpDir}" /var/rundeck/projects/"${NAME}"
sudo chown -R rundeck:rundeck /var/rundeck/projects/"${NAME}"
sudo chmod 775 /var/rundeck/projects/"${NAME}"

exit $?

# Done
