# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Nov 14 10:13:36 PST 2012
#
#/ usage: rundeck:create-job  [ --rundeck-url|-r <http://localhost:4440> ] --file|-f <> [ --api-version|-a <5>] [ --username|-u <admin>] [ --password|-p <admin>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --rundeck-url|-r) rerun_option_check $# ; RUNDECK_URL=$2 ; shift ;;
            --file|-f) rerun_option_check $# ; FILE=$2 ; shift ;;
            --api-version|-a) rerun_option_check $# ; API_VERSION=$2 ; shift ;;
            --username|-u) rerun_option_check $# ; USERNAME=$2 ; shift ;;
            --password|-p) rerun_option_check $# ; PASSWORD=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$RUNDECK_URL" ] && RUNDECK_URL="http://localhost:4440"
    [ -z "$API_VERSION" ] && API_VERSION="5"
    [ -z "$USERNAME" ] && USERNAME="admin"
    [ -z "$PASSWORD" ] && PASSWORD="admin"
    # Check required options are set
    [ -z "$RUNDECK_URL" ] && { echo >&2 "missing required option: --rundeck-url" ; return 2 ; }
    [ -z "$FILE" ] && { echo >&2 "missing required option: --file" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export RUNDECK_URL
    export FILE
    export API_VERSION
    export USERNAME
    export PASSWORD
    #
    return 0
}


# Initialize the options variables to null.
RUNDECK_URL=
FILE=
API_VERSION=
USERNAME=
PASSWORD=


