# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu Nov 15 11:55:59 PST 2012
#
#/ usage: rundeck:install  --grant-rundeck-sudo <false> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --grant-rundeck-sudo) rerun_option_check $# ; GRANT_RUNDECK_SUDO=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$GRANT_RUNDECK_SUDO" ] && GRANT_RUNDECK_SUDO="false"
    # Check required options are set
    [ -z "$GRANT_RUNDECK_SUDO" ] && { echo >&2 "missing required option: --grant-rundeck-sudo" ; return 2 ; }
    # If option variables are declared exportable, export them.
    export GRANT_RUNDECK_SUDO
    #
    return 0
}


# Initialize the options variables to null.
GRANT_RUNDECK_SUDO=


