#!/usr/bin/env bash
#
#/ command: rundeck:remove: "Remove the Rundeck Installation"
#
#/ usage: rerun rundeck:remove [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/remove/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/remove/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: rundeck:remove. ***"' ERR
set -o nounset -o pipefail


# ------------------------------
# Your implementation goes here.
# ------------------------------

sudo yum -y remove rundeck

if [ "${CLEANUP}" = "true" ]
then
   sudo yum -y remove rundeck-repo

   if ! getent passwd rundeck >/dev/null 
   then
      :
   else
      sudo userdel -f -r rundeck 
   fi
    
   if ! getent group rundeck >/dev/null 
   then
      :
   else
      sudo groupdel rundeck 
   fi
   sudo rm -rf /var/lib/rundeck /var/log/rundeck
fi

exit $?

# Done
