#!/usr/bin/env bash
#
#/ command: rundeck:stop: "Stop the rundeck service"
#
#/ usage: rerun rundeck:stop [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/stop/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/stop/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: rundeck:stop. ***"' ERR
set -o nounset -o pipefail


# ------------------------------
# Your implementation goes here.
# ------------------------------


#asynchronously execute the shutdown service script so that we may immediately monitor the log for important message 
#remember the pid so we may kill it later if needed.
sudo service rundeckd stop 

INTERVAL=2
COUNT=90

timeout $((INTERVAL*COUNT))   bash -c 'while [ 1 ]; do netstat -an |grep -q '4440.*LISTEN' || { break; }; sleep ${INTERVAL}; done'

exit $?

# Done
